apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: submit-ray-job-tekton-run
spec:
  taskRef:
    name: submit-ray-job-tekton
  params:
    - name: ray-dashboard-url
      value: http://raycluster-kuberay-head-svc.default.svc.cluster.local:8265
    - name: configmap-name
      value: ray-job-script
    - name: configmap-key
      value: ray-script.py
    - name: python-image
      value: python:3.9  # You can specify a custom Python image here
  resources:
    - name: python-script
      resourceRef:
        name: ray-job-script
